import {AiModel, computeCostsToRun} from './ai-model.model';

type MInput = Omit<AiModel, 'costsToRun' | 'deprecated' | 'deprecationInfo'>
  & { deprecated?: boolean; deprecationInfo?: string };

function m(base: MInput): AiModel {
  return {
    ...base,
    deprecated: base.deprecated ?? false,
    deprecationInfo: base.deprecationInfo ?? '',
    costsToRun: computeCostsToRun(base.inputCosts, base.outputCosts, base.reasoningFactor, base.inputFactor, base.outputFactor),
  };
}

export const AI_MODELS: AiModel[] = [
  m({
    id: 'gpt-oss-20B',
    publicName: 'GPT OSS 20B',
    modelName: 'gpt-oss-20B',
    inputCosts: 0.07,
    outputCosts: 0.3,
    contextWindow: 128000,
    maxInputTokens: 128000,
    maxOutputTokens: 128000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 24,
    codingIntelligence: 19,
    agenticIntelligence: 28,
    releaseDate: '2025-08-05',
    cutoffDate: '2024-06-01',
    reasoning: true,
    reasoningFactor: 58.32,
    inputFactor: 140.32,
    outputFactor: 3.02,
    tokensPerSecond: 269,
    inputProcessingTime: 0.7,
    thinkingTime: 7.4,
    outputTime: 1.9,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'gpt-oss-20B-local',
    publicName: 'GPT OSS 20B Q4 (Local)',
    modelName: 'gpt-oss-20B',
    inputCosts: 0.007,
    outputCosts: 0.02,
    contextWindow: 128000,
    maxInputTokens: 128000,
    maxOutputTokens: 128000,
    localModel: true,
    minVramRequirement: 16,
    overallIntelligence: 22,
    codingIntelligence: 17,
    agenticIntelligence: 26,
    releaseDate: '2025-08-05',
    cutoffDate: '2024-06-01',
    reasoning: true,
    reasoningFactor: 58.32,
    inputFactor: 140.32,
    outputFactor: 3.02,
    tokensPerSecond: 269,
    inputProcessingTime: 0.7,
    thinkingTime: 7.4,
    outputTime: 1.9,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'gpt-oss-120B',
    publicName: 'GPT OSS 120B',
    modelName: 'gpt-oss-120B',
    inputCosts: 0.15,
    outputCosts: 0.6,
    contextWindow: 128000,
    maxInputTokens: 128000,
    maxOutputTokens: 128000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 33,
    codingIntelligence: 29,
    agenticIntelligence: 38,
    releaseDate: '2025-08-05',
    cutoffDate: '2024-06-01',
    reasoning: true,
    reasoningFactor: 73.42,
    inputFactor: 138.3,
    outputFactor: 4.28,
    tokensPerSecond: 210,
    inputProcessingTime: 0.9,
    thinkingTime: 9.5,
    outputTime: 2.4,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'gpt-oss-120B-local',
    publicName: 'GPT OSS 120B Q4 (Local)',
    modelName: 'gpt-oss-120B',
    inputCosts: 0.015,
    outputCosts: 0.06,
    contextWindow: 128000,
    maxInputTokens: 128000,
    maxOutputTokens: 128000,
    localModel: true,
    minVramRequirement: 80,
    overallIntelligence: 31,
    codingIntelligence: 27,
    agenticIntelligence: 36,
    releaseDate: '2025-08-05',
    cutoffDate: '2024-06-01',
    reasoning: true,
    reasoningFactor: 73.42,
    inputFactor: 138.3,
    outputFactor: 4.28,
    tokensPerSecond: 210,
    inputProcessingTime: 0.9,
    thinkingTime: 9.5,
    outputTime: 2.4,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'qwen3.5-9B-local',
    publicName: 'Qwen3.5 9B Q4 (Local)',
    modelName: 'qwen3.5-9B',
    inputCosts: 0.007,
    outputCosts: 0.0175,
    contextWindow: 262144,
    maxInputTokens: 0,
    maxOutputTokens: 0,
    localModel: true,
    minVramRequirement: 24,
    overallIntelligence: 30,
    codingIntelligence: 23,
    agenticIntelligence: 35,
    releaseDate: '2026-03-02',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 190.05,
    inputFactor: 517.88,
    outputFactor: 11.76,
    tokensPerSecond: 87,
    inputProcessingTime: 0.7,
    thinkingTime: 23,
    outputTime: 5.8,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'qwen3.5-27B-local',
    publicName: 'Qwen3.5 27B Q4 (Local)',
    modelName: 'qwen3.5-27B',
    inputCosts: 0.03,
    outputCosts: 0.24,
    contextWindow: 262144,
    maxInputTokens: 0,
    maxOutputTokens: 0,
    localModel: true,
    minVramRequirement: 48,
    overallIntelligence: 40,
    codingIntelligence: 33,
    agenticIntelligence: 53,
    releaseDate: '2026-02-24',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 87.62,
    inputFactor: 214.65,
    outputFactor: 10.24,
    tokensPerSecond: 83,
    inputProcessingTime: 5.6,
    thinkingTime: 24.2,
    outputTime: 6.1,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'qwen3.5-35B-local',
    publicName: 'Qwen3.5 35B Q4 (Local)',
    modelName: 'qwen3.5-35B',
    inputCosts: 0.025,
    outputCosts: 0.2,
    contextWindow: 262144,
    maxInputTokens: 0,
    maxOutputTokens: 0,
    localModel: true,
    minVramRequirement: 62,
    overallIntelligence: 35,
    codingIntelligence: 28,
    agenticIntelligence: 42,
    releaseDate: '2026-02-24',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 89.91,
    inputFactor: 402.96,
    outputFactor: 10.57,
    tokensPerSecond: 174,
    inputProcessingTime: 2.2,
    thinkingTime: 11.5,
    outputTime: 2.9,
    deprecated: true,
    deprecationInfo: 'Use the predecessor instead: Qwen3.6 35B A3B',
  }),
  m({
    id: 'qwen3-coder-30B',
    publicName: 'Qwen3 Coder 30B (Non-Thinking)',
    modelName: 'qwen3-coder-30B',
    inputCosts: 0.15,
    outputCosts: 0.6,
    contextWindow: 262144,
    maxInputTokens: 262144,
    maxOutputTokens: 131072,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 20,
    codingIntelligence: 19,
    agenticIntelligence: 21,
    releaseDate: '2025-05-14',
    cutoffDate: null,
    reasoning: false,
    reasoningFactor: 0,
    inputFactor: 95.87,
    outputFactor: 13.2,
    tokensPerSecond: 108,
    inputProcessingTime: 2.8,
    thinkingTime: 0,
    outputTime: 4.6,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'qwen3-coder-30B-local',
    publicName: 'Qwen3 Coder 30B Q4 (Local; Non-Thinking)',
    modelName: 'qwen3-coder-30B',
    inputCosts: 0.045,
    outputCosts: 0.225,
    contextWindow: 262144,
    maxInputTokens: 262144,
    maxOutputTokens: 131072,
    localModel: true,
    minVramRequirement: 64,
    overallIntelligence: 18,
    codingIntelligence: 17,
    agenticIntelligence: 19,
    releaseDate: '2025-05-14',
    cutoffDate: null,
    reasoning: false,
    reasoningFactor: 0,
    inputFactor: 95.87,
    outputFactor: 13.2,
    tokensPerSecond: 108,
    inputProcessingTime: 2.8,
    thinkingTime: 0,
    outputTime: 4.6,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'qwen3-235B',
    publicName: 'Qwen3 235B',
    modelName: 'qwen3-235B',
    inputCosts: 0.22,
    outputCosts: 0.88,
    contextWindow: 262144,
    maxInputTokens: 262144,
    maxOutputTokens: 131072,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 30,
    codingIntelligence: 23,
    agenticIntelligence: 30,
    releaseDate: '2025-04-29',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 60.71,
    inputFactor: 53.66,
    outputFactor: 2.62,
    tokensPerSecond: 33,
    inputProcessingTime: 3.2,
    thinkingTime: 61.4,
    outputTime: 15.4,
    deprecated: true,
    deprecationInfo: 'This model is outdated (12+ months).',
  }),
  m({
    id: 'glm-4.7-flash',
    publicName: 'GLM 4.7 Flash (30B)',
    modelName: 'glm-4.7-flash',
    inputCosts: 0.07,
    outputCosts: 0.4,
    contextWindow: 200000,
    maxInputTokens: 200000,
    maxOutputTokens: 128000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 30,
    codingIntelligence: 26,
    agenticIntelligence: 46,
    releaseDate: '2026-01-14',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 55.98,
    inputFactor: 206.36,
    outputFactor: 7.94,
    tokensPerSecond: 82,
    inputProcessingTime: 1.4,
    thinkingTime: 24.4,
    outputTime: 6.1,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'glm-4.7-flash-local',
    publicName: 'GLM 4.7 Flash Q4 (Local)',
    modelName: 'glm-4.7-flash',
    inputCosts: 0.007,
    outputCosts: 0.04,
    contextWindow: 200000,
    maxInputTokens: 200000,
    maxOutputTokens: 128000,
    localModel: true,
    minVramRequirement: 42,
    overallIntelligence: 28,
    codingIntelligence: 24,
    agenticIntelligence: 44,
    releaseDate: '2026-01-14',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 55.98,
    inputFactor: 206.36,
    outputFactor: 7.94,
    tokensPerSecond: 82,
    inputProcessingTime: 1.4,
    thinkingTime: 24.4,
    outputTime: 6.1,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'minimax-m2.1',
    publicName: 'MiniMax M2.1 (229B)',
    modelName: 'minimax-m2.1',
    inputCosts: 0.3,
    outputCosts: 1.2,
    contextWindow: 200000,
    maxInputTokens: 196000,
    maxOutputTokens: 8192,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 39,
    codingIntelligence: 33,
    agenticIntelligence: 47,
    releaseDate: '2025-12-23',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 51.05,
    inputFactor: 147.93,
    outputFactor: 7.35,
    tokensPerSecond: 74,
    inputProcessingTime: 1.9,
    thinkingTime: 27,
    outputTime: 6.7,
    deprecated: true,
    deprecationInfo: 'Use the predecessor instead: MiniMax M2.5',
  }),
  m({
    id: 'claude-haiku-4.5',
    publicName: 'Claude Haiku 4.5',
    modelName: 'claude-haiku-4.5',
    inputCosts: 1.1,
    outputCosts: 5.5,
    contextWindow: 200000,
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 37,
    codingIntelligence: 33,
    agenticIntelligence: 40,
    releaseDate: '2025-10-15',
    cutoffDate: '2025-02-28',
    reasoning: true,
    reasoningFactor: 79.29,
    inputFactor: 146.62,
    outputFactor: 7.99,
    tokensPerSecond: 92,
    inputProcessingTime: 23.1,
    thinkingTime: 0,
    outputTime: 5.4,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'claude-sonnet-4.6',
    publicName: 'Claude Sonnet 4.6',
    modelName: 'claude-sonnet-4.6',
    inputCosts: 3.3,
    outputCosts: 16.5,
    contextWindow: 1000000,
    maxInputTokens: 1000000,
    maxOutputTokens: 64000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 52,
    codingIntelligence: 51,
    agenticIntelligence: 63,
    releaseDate: '2026-02-17',
    cutoffDate: '2025-08-01',
    reasoning: true,
    reasoningFactor: 187,
    inputFactor: 328.99,
    outputFactor: 11.16,
    tokensPerSecond: 47,
    inputProcessingTime: 116.6,
    thinkingTime: 0,
    outputTime: 10.6,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'claude-opus-4.6',
    publicName: 'Claude Opus 4.6',
    modelName: 'claude-opus-4.6',
    inputCosts: 5.5,
    outputCosts: 27.5,
    contextWindow: 1000000,
    maxInputTokens: 1000000,
    maxOutputTokens: 128000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 53,
    codingIntelligence: 48,
    agenticIntelligence: 68,
    releaseDate: '2026-02-05',
    cutoffDate: '2025-05-01',
    reasoning: true,
    reasoningFactor: 148.73,
    inputFactor: 209.12,
    outputFactor: 8.23,
    tokensPerSecond: 41,
    inputProcessingTime: 13.2,
    thinkingTime: 0,
    outputTime: 12.2,
    deprecated: true,
    deprecationInfo: 'Use the predecessor instead: Claude Opus 4.7',
  }),
  m({
    id: 'claude-opus-4.7',
    publicName: 'Claude Opus 4.7',
    modelName: 'claude-opus-4.7',
    inputCosts: 5.5,
    outputCosts: 27.5,
    contextWindow: 1_000_000,
    maxInputTokens: 1_000_000,
    maxOutputTokens: 128_000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 57,
    codingIntelligence: 53,
    agenticIntelligence: 71,
    releaseDate: '2026-04-16',
    cutoffDate: "2026-01-01",
    reasoning: true,
    reasoningFactor: 92.76,
    inputFactor: 371,
    outputFactor: 19.17,
    tokensPerSecond: 44,
    inputProcessingTime: 11.3,
    thinkingTime: 0,
    outputTime: 11.4,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'minimax-m2.5',
    publicName: 'MiniMax M2.5',
    modelName: 'minimax-m2.5',
    inputCosts: 0.3,
    outputCosts: 1.2,
    contextWindow: 1_000_000,
    maxInputTokens: 1_000_000,
    maxOutputTokens: 8_192,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 42,
    codingIntelligence: 37,
    agenticIntelligence: 56,
    releaseDate: '2026-02-12',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 50.99,
    inputFactor: 190.24,
    outputFactor: 5.27,
    tokensPerSecond: 65,
    inputProcessingTime: 1.8,
    thinkingTime: 30.8,
    outputTime: 7.7,
    deprecated: false,
    deprecationInfo: '',
  }),
  m({
    id: 'qwen3.6-35B-a3B-local',
    publicName: 'Qwen3.6 35B A3B Q4 (Local)',
    modelName: 'qwen3.6-35B-a3B',
    inputCosts: 0.0375,
    outputCosts: 0.225,
    contextWindow: 262_144,
    maxInputTokens: 262_144,
    maxOutputTokens: 32_768,
    localModel: true,
    minVramRequirement: 62,
    overallIntelligence: 41,
    codingIntelligence: 33,
    agenticIntelligence: 56,
    releaseDate: '2026-04-14',
    cutoffDate: null,
    reasoning: true,
    reasoningFactor: 131.72,
    inputFactor: 270.35,
    outputFactor: 11.47,
    tokensPerSecond: 216,
    inputProcessingTime: 2.5,
    thinkingTime: 9.3,
    outputTime: 2.3,
    deprecated: false,
    deprecationInfo: '',
  })
];

const _maxCostsToRun = Math.max(...AI_MODELS.map(mm => mm.costsToRun));
export const COSTS_TO_RUN_SCALE = _maxCostsToRun > 0 ? 100 / _maxCostsToRun : 1;
for (const mm of AI_MODELS) mm.costsToRun *= COSTS_TO_RUN_SCALE;
