import {AiModel, computeCostsToRun} from './ai-model.model';

function m(base: Omit<AiModel, 'costsToRun'>): AiModel {
  return { ...base, costsToRun: computeCostsToRun(base.inputCosts, base.outputCosts) };
}

export const AI_MODELS: AiModel[] = [
  m({
    id: 'gpt-oss-20b-litellm',
    publicName: 'GPT OSS 20b',
    modelName: 'gpt-oss-20b',
    inputCosts: 0.07,
    outputCosts: 0.3,
    contextWindow: 128000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 24,
    codingIntelligence: 19,
    agenticIntelligence: 28,
  }),
  m({
    id: 'gpt-oss-20B-local',
    publicName: 'GPT OSS 20B (Local)',
    modelName: 'gpt-oss-20B',
    inputCosts: 0.035,
    outputCosts: 0.15,
    contextWindow: 128000,
    localModel: true,
    minVramRequirement: 40,
    overallIntelligence: 24,
    codingIntelligence: 19,
    agenticIntelligence: 28,
  }),
  m({
    id: 'gpt-oss-120B',
    publicName: 'GPT OSS 120B',
    modelName: 'gpt-oss-120B',
    inputCosts: 0.15,
    outputCosts: 0.6,
    contextWindow: 128000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 33,
    codingIntelligence: 29,
    agenticIntelligence: 38,
  }),
  m({
    id: 'qwen3.5-9B-local',
    publicName: 'Qwen3.5 9B (Local)',
    modelName: 'qwen3.5-9B',
    inputCosts: 0.018,
    outputCosts: 0.07,
    contextWindow: 262000,
    localModel: true,
    minVramRequirement: 18,
    overallIntelligence: 32,
    codingIntelligence: 25,
    agenticIntelligence: 37,
  }),
  m({
    id: 'qwen3.5-27B-local',
    publicName: 'Qwen3.5 27B (Local)',
    modelName: 'qwen3.5-27B',
    inputCosts: 0.035,
    outputCosts: 0.15,
    contextWindow: 262000,
    localModel: true,
    minVramRequirement: 54,
    overallIntelligence: 42,
    codingIntelligence: 35,
    agenticIntelligence: 55,
  }),
  m({
    id: 'qwen3-coder-30B-litellm',
    publicName: 'Qwen3 Coder 30B',
    modelName: 'qwen3-coder-30B',
    inputCosts: 0.15,
    outputCosts: 0.6,
    contextWindow: 262000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 20,
    codingIntelligence: 19,
    agenticIntelligence: 21,
  }),
  m({
    id: 'qwen3-coder-30B-local',
    publicName: 'Qwen3 Coder 30B (Local)',
    modelName: 'qwen3-coder-30B',
    inputCosts: 0.075,
    outputCosts: 0.3,
    contextWindow: 262000,
    localModel: true,
    minVramRequirement: 60,
    overallIntelligence: 20,
    codingIntelligence: 19,
    agenticIntelligence: 21,
  }),
  m({
    id: 'qwen3-235b',
    publicName: 'Qwen3 235B',
    modelName: 'qwen3-235B',
    inputCosts: 0.22,
    outputCosts: 0.88,
    contextWindow: 262000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 28,
    codingIntelligence: 21,
    agenticIntelligence: 27,
  }),
  m({
    id: 'glm-4.7-flash',
    publicName: 'GLM 4.7 Flash',
    modelName: 'glm-4.7-flash',
    inputCosts: 0.07,
    outputCosts: 0.4,
    contextWindow: 200000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 30,
    codingIntelligence: 26,
    agenticIntelligence: 46,
  }),
  m({
    id: 'glm-4.7-flash-local',
    publicName: 'GLM 4.7 Flash (Local)',
    modelName: 'glm-4.7-flash',
    inputCosts: 0.035,
    outputCosts: 0.2,
    contextWindow: 200000,
    localModel: true,
    minVramRequirement: 60,
    overallIntelligence: 30,
    codingIntelligence: 26,
    agenticIntelligence: 46,
  }),
  m({
    id: 'minimax-m2.1',
    publicName: 'MiniMax M2.1',
    modelName: 'minimax-m2.1',
    inputCosts: 0.3,
    outputCosts: 1.2,
    contextWindow: 200000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 39,
    codingIntelligence: 33,
    agenticIntelligence: 47,
  }),
  m({
    id: 'claude-haiku-4.5',
    publicName: 'Claude Haiku 4.5',
    modelName: 'claude-haiku-4.5',
    inputCosts: 1.1,
    outputCosts: 5.5,
    contextWindow: 200000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 37,
    codingIntelligence: 33,
    agenticIntelligence: 40,
  }),
  m({
    id: 'claude-sonnet-4.6',
    publicName: 'Claude Sonnet 4.6',
    modelName: 'claude-sonnet-4.6',
    inputCosts: 3.3,
    outputCosts: 16.5,
    contextWindow: 200000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 44,
    codingIntelligence: 46,
    agenticIntelligence: 62,
  }),
  m({
    id: 'claude-opus-4.6',
    publicName: 'Claude Opus 4.6',
    modelName: 'claude-opus-4.6',
    inputCosts: 5.5,
    outputCosts: 27.5,
    contextWindow: 1000000,
    localModel: false,
    minVramRequirement: 0,
    overallIntelligence: 46,
    codingIntelligence: 48,
    agenticIntelligence: 64,
  }),
];
